config/routes.rb
Rails.application.routes.draw do
  resources :recorded_times

end

app/models/recorded_time.rb
class RecordedTime < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recorded_times_controller.rb
class RecordedTimesController < ApplicationController
  before_action :set_recorded_time, only: [:show, :edit, :update, :destroy]

  # GET /recorded_times
  # GET /recorded_times.json
  def index
    @recorded_times = RecordedTime.all
  end

  # GET /recorded_times/1
  # GET /recorded_times/1.json
  def show
  end

  # GET /recorded_times/new
  def new
    @recorded_time = RecordedTime.new
  end

  # GET /recorded_times/1/edit
  def edit
  end

  # POST /recorded_times
  # POST /recorded_times.json
  def create
    @recorded_time = RecordedTime.new(recorded_time_params)

    respond_to do |format|
      if @recorded_time.save
        format.html { redirect_to @recorded_time, notice: 'Recorded time was successfully created.' }
        format.json { render :show, status: :created, location: @recorded_time }
      else
        format.html { render :new }
        format.json { render json: @recorded_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recorded_times/1
  # PATCH/PUT /recorded_times/1.json
  def update
    respond_to do |format|
      if @recorded_time.update(recorded_time_params)
        format.html { redirect_to @recorded_time, notice: 'Recorded time was successfully updated.' }
        format.json { render :show, status: :ok, location: @recorded_time }
      else
        format.html { render :edit }
        format.json { render json: @recorded_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recorded_times/1
  # DELETE /recorded_times/1.json
  def destroy
    @recorded_time.destroy
    respond_to do |format|
      format.html { redirect_to recorded_times_url, notice: 'Recorded time was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recorded_time
      @recorded_time = RecordedTime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recorded_time_params
      params.require(:recorded_time).permit(:number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recorded_times_helper.rb
module RecordedTimesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecordTime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recorded_times/_form.html.erb
<%= form_for(@recorded_time) do |f| %>
  <% if @recorded_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recorded_time.errors.count, "error") %> prohibited this recorded_time from being saved:</h2>

      <ul>
      <% @recorded_time.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recorded_times/edit.html.erb
<h1>Editing recorded_time</h1>

<%= render 'form' %>

<%= link_to 'Show', @recorded_time %> |
<%= link_to 'Back', recorded_times_path %>

app/views/recorded_times/index.html.erb
<center><h3>Final Countdown</h3>

<h1><span id="count"></span></h1>

<br><br>

<a id="current">Record <span></span></a>
<br>
<br>
<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recorded_times.each do |recorded_time| %>
      <tr>
        <td><%= recorded_time.number %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>

app/views/recorded_times/new.html.erb
<h1>New recorded_time</h1>

<%= render 'form' %>

<%= link_to 'Back', recorded_times_path %>

app/views/recorded_times/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @recorded_time.number %>
</p>

<%= link_to 'Edit', edit_recorded_time_path(@recorded_time) %> |
<%= link_to 'Back', recorded_times_path %>